version: '3.0'
services:
  web:
    image: aishnee/project1-web
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - mynetwork
      
  mysql:
    image: aishnee/project1-mysql
    ports: 
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Gungun/123
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:


