on: [push]
jobs:
  job_1:
    name: Creating web image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
       name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{secrets.DOCKERHUB_USERNAME}}
         password: ${{secrets.DOCKERHUB_PASSWORD}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mysql/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project1-mysql:latest
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./sentiment/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project1-web:latest
